### ISSUE TITLE
Discussion about NEF format

### ISSUE THREAD

**Issue by davidarndt** [NMRExchangeFormat/NEF#10]
Hi,

I'm David Arndt, from Dr. David Wishart's lab. I'm updating some of our lab's servers to handle the new NEF format. Dr. Wishart forwarded an email to me from Dr. Rasmus Fogh, which read in part, "We hope to convince you to use the account on GitHub for communiation, proposals, and sharing test results … ." So I'm wondering whether the intent is for people to raise questions or make comments on the issues tracker on GitHub, or whether some other means of communication is preferred.

One question I have is: Is it part of the specification for _nef_chemical_shift.value_uncertainty to optionally use scientific notation, as in the example file CCPN_H1GI_alt.nef? Or was it an oversight that led to the inclusion of those values?

Thanks

**Comment by rhfogh** [comment]
There is no specification in the format on how to write floating point numbers, so any standard way of doing it should be supported. In Python, either 5.1E6 or 51000000.0 should be read correctly, and either may be used. Unless this gives problems for other languages (does it?) I think it would be best to leave it at that.

Your example confused me a bit - I did not find any examples of scientific notation in CCPN_H1GI_alt.nef, but there are some in specification/Commented_Example.nef. Anyway, the point is the same no matter what is in which example file.

**Comment by davidarndt** [comment]
I have not had any problems parsing the numbers in scientific notation, but was wondering what values could be expected since this would affect how one would write a parser. And there are a few cases of scientific notation in CCPN_H1GI_alt.nef, e.g. on line 340 there is 2.6973983046972182e-06.

I'm not sure how settled the specification is for NEF format, but I had a couple of other comments/questions. I will start other issues for them on GitHub. Thanks.

**Comment by rhfogh** [comment]
One proposal, taken from https://docs.python.org/3/reference/lexical_analysis.html#floating and http://en.cppreference.com/w/cpp/language/floating_literal, would be this:

"A floating-point literals have two syntaxes. The first one consists of the following parts: 
 nonempty sequence of decimal digits containing a decimal point character (defines significand) 
(optional) e or E followed with optional minus or plus sign and nonempty sequence of decimal digits (defines exponent) 

The second one consists of the following parts: 
 nonempty sequence of decimal digits (defines significant) 
e or E followed with optional minus or plus sign and nonempty sequence of decimal digits (defines exponent)"

This excludes suffixes to distinguish between floats and longs (as allowed for C++), since we are passing around a value but not specifying how it should be stored.

Being mainly a Python programmer I may not be the best person to judge on this. Does anyone have an alternative proposal, or problems with this one?
