### ISSUE TITLE
Wildcard atom sets for non-terminal Threonine

### ISSUE THREAD

**Issue by kumar-physics** [NMRExchangeFormat/NEF#40]
This table looks so strange for me. The main purpose of NEF is to exchange data **between softwares.** 
Lets say software 'A' writes out an output chemical shift for HG%, how does another software 'B' interprets that? There are multiple ways it can interpret according to your table. Which interpretation is correct? If this data pass through several softwares with unclear and inconsistent definition, the final output will be questionable . These type of misinterpretation might propagate and amplify from one software to another, and as a result the data quality will be lost

**Comment by kumar-physics** [comment]
Is HG* and HG% are equivalent ? If not what is the difference ?

**Comment by rhfogh** [comment]
The information is actually completely unambiguous. The point is that you can only evaluate it *once you know what type of residue it refers to*. But since it is mandatory for NEF files to give the sequence, you will know the correct residue topology  whenever you actually have a complete assignment. 

If someone gave a chemical shift for a THR HG%, it would have a perfectly unequivocal meaning:
It would say that the four protons HG1, HG21, HG22, and HG23 had exactly the same chemical shift and should be r-6 averaged together if this assignment appeared in a restraint list. Of course this is not a sensible thing to do (it is more likely to be an error), but the meaning is clear enough. It is up to programs to not say what they do not mean.

HG\* and HG% are different expressions that have to be evaluated against the atoms in the relevant residue, and that in this (and indeed most) cases evaluate to the same result. Indeed, Overview.md says that *"In normal current usage '%' wildcard expressions will be used for NMR-equivalent atoms, and '\*' expressions must only  be used where '%' expressions would not suffice."* The only practical need for '\*' that I can see is in expressions like '\*', 'H\*', 'C\*' etc.

You do get ambiguities when you do not know the residueType, be it that it is set to 'UNK' or '.', or a topology file you do not have. In a case like 'X.@57.UNK.HB%' you do not know if HB% refers to a CH2 or a CH3 group. But considering how much else you do not know, maybe that is not the biggest problem in this case.

To give you a parallel, a code like 'HB%' is a little like the normal English phrase "the president's daughters". You cannot say how many people that refers to - or indeed if it refers to anybody at all - unless you know which president you are talking about, and how many daughters he has.

**Comment by kumar-physics** [comment]
Can 'X' be replaced with '%' as in XPLOR output ?

**Comment by rhfogh** [comment]
They mean diferent things, but they can refer more or less to the same atoms. To take e.g. SER beta, the following three chemical shift designations give the same information:

         A  10  HIS  HB2   3.201    0.02
         A  10  HIS  HB3   3.201    0.02

         A  10  HIS  HBX   3.201    0.02
         A  10  HIS  HBY   3.201    0.02

         A  10  HIS  HB%   3.201    0.02

Similarly, the following three restraints hold almost the same information, to wit that the R-6 sum
of the distances between 23 PHE HN and 23 PHE HB2 and HB3 adds up to a distance of 4.22A. 

         1217  1217  .  A  23  PHE  H     A  23  PHE  HB2   1  4.22  .  .  1.8  4.64  .
         1218  1217  .  A  23  PHE  H     A  23  PHE  HB3   1  4.22  .  .  1.8  4.64  .

         1217  1217  .  A  23  PHE  H     A  23  PHE  HBX   1  4.22  .  .  1.8  4.64  .
         1218  1217  .  A  23  PHE  H     A  23  PHE  HBY   1  4.22  .  .  1.8  4.64  .

         1217  1217  .  A  23  PHE  H     A  23  PHE  HB%   1  4.22  .  .  1.8  4.64  .
(though you should change the restraint limits a mit inthe last case to get the same restraining effect).

Of course you can only exchange 'X'/'Y' or '2'/'3' with '%' when the chemical shifts are identical (in the first example), or when the atoms are symmetrically involved in the restraint (in the second example).

If you had, instead, 

         1217  1217  .  A  23  PHE  H     A  23  PHE  HBX   1  5.2  .  .  1.8  5.9  .
         1218  1217  .  A  23  PHE  H     A  23  PHE  HBY   1  3.5  .  .  1.8  4.2  .

Then the alternatives would have a different meaning.

         1217  1217  .  A  23  PHE  H     A  23  PHE  HB2   1  5.2  .  .  1.8  5.9  .
         1218  1217  .  A  23  PHE  H     A  23  PHE  HB3   1  3.5  .  .  1.8  4.2  .
would mean that the beta protons were stereospecifically assigned, ande a restraint involving
HB% would mean that you restrained the r-6 sum of the contributions instead of restraining them individually.

**Comment by kumar-physics** [comment]
form XplorNIH-simple.nef

> 63 .  5 LEU HD2% . 30 PHE  HB% 4.0 1.8 5.5 
> 64 .  5 LEU HD2% . 30 PHE  HB% 3.0 0.8 3.8 

Could you explain this? Is it correct?

**Comment by kumar-physics** [comment]
The meaning of 'X' 'Y' and '%' in terms of restraints has to be documented properly. Your explanation helps to understand just one specific case. For example the use of restrain_id and restrain_combination_id needs more examples and explanation. In your why would you used same restrain_id for stereo specifically assigned restraints. It should be ANDed right!. 

what is the difference between
`  1217  1217  .  A  23  PHE  H     A  23  PHE  HBX   1  5.2  .  .  1.8  5.9  .
     1218  1217  .  A  23  PHE  H     A  23  PHE  HBY   1  3.5  .  .  1.8  4.2  .`

and 
`  1217  1217  .  A  23  PHE  H     A  23  PHE  HBX   1  5.2  .  .  1.8  5.9  .
     1218  1218  .  A  23  PHE  H     A  23  PHE  HBY   1  3.5  .  .  1.8  4.2  .`

probably HBX and HBY are well separated peaks, so it will lead to two restraints, should we treat as one restrain or two?

**Comment by rhfogh** [comment]
It is correct, in the sense that it does not break the rules. As it happens, restraint 63 is redundant (and restraint 64 probably has a typo - I suspect that should have been '1.8' not '0.8'). But it almost certainly was created from a different original by throwing away information.

I can explain what happened:

A tricky problem has always been that structures and dynamics programs have stereospecific assignment (i.e. they distinguish between the pro-R and pro-S proton in a methylene group etc.), whereas experimental spectroscopy does not. We can only see that there are two distinct beta protons, but in most cases we cannot say which is the pro-R and which is the pro-S. The first solution was to put the distance restraints in as restraints to the midpoint between the two protons, and add 0.9A to the restrained distance to compensate. This made the restraints looser than they would otherwise have been (throwing way information).  Structure refinement has made various hacks to improve on that (one was to make restraints to the individual protons, but to artificially let the topology of the carbon flip between R and S during the simulation). A program like ARIA can generate structure ensembles where the same NMR frequency can be assigned to e.g. HB2 in one of the models but to HB3 in another one, whereas e.g. CYANA always has the same assignments across an ensemble. 

Anyway, it is quite messy to figure out when the atoms given as 'HB2' and 'HB3' in a restraint file actually refer to the correct atoms, when they are swapped, and whether this status is the same for all models of an ensemble. A common solution is to go back to the way things were done at first, and replace restraints to individual protons with restraints to both of them at once (or to the centroid). That avoids a lot of work and a lot of errors - at the cost of throwing away information. That is surely what Charles has done here, and other programs (like CING) does the same thing.

In fact, the point of the 'X' and 'Y' atom names, is that it allows you to represent accurately the information you actually have. You can specify which restraints involve proton X, with a known chemical shift, and which restraints involve proton Y, with another chemical shift, without having to invent or guess information about which one is pro-R and which one is pro-S. Which programs can deal correctly with this information is another question, but with NEF at least the information will be available.

**Comment by rhfogh** [comment]
The use of the restraint_combination_id does indeed need more explanation. I shall have to look more closely at it, it is on kmy TODO list - but it will to be today! It does not help that I have no test data, except CommentedExample that I made up myself. In fact I think that CYANA is the only program that actually needs combination_id.

The difference in your example is (or should be) that one case is two different restraints, which are AND'ed, and the other case is one restraint with two contributions, which are OR'ed (or rather r-6 summed). I cannot quite guarantee that I got the syntax right (I cannot do the same level of checking in a fast discussion as in a test file), but that was the idea.

As for how they should be treated:
If they are given as one restraint they should be treated as one restraint (and OR'ed); if they are given as two restraints they should be treated as two restraints (and AND'ed). That decision lies with the program that writes the file, not with the user.

**Comment by rhfogh** [comment]
'HG2%' v. 'HG%%' - or alternative wildcards
 
 On second thoughts, I think we should limit the use of wildcard expressions for stereoequivalent
 groups of nuclei to expressions containing as many non-wildcard letters as 
 possible and a single '%'. In practice:
 ALA: HB%
 ILE: HG1%, HG2%, and HD1%
 THR: HG2%
 VAL: HG1%, HG2%, HG%, and CG%
 LEU: HB%, HD1%, HD2%, HD%, and CD%
 TYR: HB%, HD%, HE%, CD%, and CE%
 MET: HB%, HG%, and HE%
 ASN: HB%, HD%
 ARG: HB%, HG%, HD%, HH1%, HH2%, HH%
 etc.
 Similar principles would be used for other cases of symmetrical branching,
 including hypothetical cases like 'CR(CH3CH3)2, para-chloro-cyclohexyl, ...
 Other wildcard expressions are legal, but programs would not be required
 to interpret them except in contexts where they normally deal with ad-hoc
 atom sets.
 
 CCPN would use 'HG2%' to indicate e.g. THR gamma methyl protons,
 whereas XPLOR seems to use 'HG%%'. Both expressions evaluate to the same
 set of protons. The same would be the case for e.g. 'H*2%' or 'H*%%'.
 Currently CcpNMr Analysis would read either expression, but only 'HG2%' would
 be recognised as the THR methyl group (known to be bound to THR CG2 etc., 
 counting in assignment statistics, etc.).
 The other expressions would be kept unchanged and re-exported, but would
 be interpreted as 'anonymous, unassigned', except in coontexts that expliclty 
 converted regular expressions to sets of atoms.
 
 The question is whether all programs have a duty to interpret all possible
 regular expressions? Or whether we can say that only some expressions are
 universally understood? The documentation currently says, essentially, that '*' 
 should only be used where '%' will not do,  which does exclude some candidates, but
 still leaves the question open.
