### ISSUE TITLE
wildcard for TYR

### ISSUE THREAD

**Issue by kumar-physics** [NMRExchangeFormat/NEF#47]
In [this](https://github.com/NMRExchangeFormat/NEF/blob/master/data/CCPN_CASD/2loj_docr.nef) file, for the residue  49 TYR   side chain ambiguities are expressed in 'X' and 'Y' in the chemical shift saveframe, but in restrain section it is represented as '%' . Does it have any explanation or just a typo?

**Comment by rhfogh** [comment]
This is legal, and likely quite normal. 'HD%' means, in normal english 'both HD protons'. Even if HDX and HDY  actually have distinct chemical shifts, there may well be restraints that are referred to 'HD%', be it for convenience, or because the resolution in a given experiment does not allow you to distinguish the two.

Now, in this particular case it would have been cleaner if the chemical shifts had been specified to 'HD%', 'HE%', 'CD%', 'CE%' - given that the chemical shifts are identical within each group - but whoever generated this restraint list chose to do it differently, and that is something one has to be prepared to deal with.

**Comment by kumar-physics** [comment]
I came to know that mmCIF  (coordinate file) will have  a column (NEF atom name against each IUPAC atom) to facilitate the validation. I wonder how do you handle the above mentioned cause. Will the NEF column in the mmCIF have 3 names(HDX,HDY,HD%)?
