### ISSUE TITLE
why residue_name is called residue_type in NEF? 

### ISSUE THREAD

**Issue by kumar-physics** [NMRExchangeFormat/NEF#54]
Is there any special reason to call residue_name as residue_type? residue_type may have many different meanings like standard vs non-standard or hydrophobic or acidic or aromatic .....etc. 
nef dictionary also describe this tag as  "The author provided residue **name**." , but still it is called residue_type.
 why don't you just call it as residue_name? May be in future for some reason if you want to include a tag for residue type, you need to rename the existing tag or call residue type as residue_something_else. If there is no good reason to call this tag as reside_type, it is better to change the tag now itself.

**Comment by rhfogh** [comment]
It is arguable whether 'residue_name' or 'residue_type' is the better name. It depends how you think about it. Both have their advantages. As it happens, I personally prefer 'residue_type'. The object is e.g. Ala 145, its type is 'ALA', and its name, would be something like '145.ALA'. Much like e.g. a BA airplane: 'Boeing 757' would be the 'airplane_type', while the 'airplane_name' would be something like 'City of Glasgow'. 

But it does not matter too much, really. Either version is understandable to the spectroscopist. If we were just starting to make the NEF format, I would agree to use 'residue_name', for consistency with BMRB. As the format is already made and largely implemented at this point, the question is whether the consortium is willing to put up with the extra work that a change would require. I suspect not, but if you can make a change proposal and convince the consortium to accept it, I do not think CCPN will particularly object.

**Comment by kumar-physics** [comment]
"**As the format is already made and largely implemented at this point**". I disagree with this point. Till now I haven't seen any real support or output from the software developers other than CCPN. 
Moreover I am still not clear with the terms "NEF consortium" and "Software developers" . I assume software developers are the part of "NEF Consortium"  and I expect them to participate the GitHub activities. 
I am not asking you to be consistent with BMRB, but I am asking to be consistent with majority of the community. I haven't  seen ALA is called as residue_type except in NEF. I don't think NEF consortium or software developers will object when you tag ALA as residue_name. You haven't answered what happens in future if you want to add a tag for residue_type?. 
**But it does not matter too much, really**- NO, It does matter. I have no problem to map NEF residue_type to STAR residue_name, but I am worrying about the expandability of NEF. If you try to expand NEF to accommodate more information(like residue_type), then you will be in trouble. So its better to change now.

**Comment by perzeus** [comment]
In this case I have to agree with Kumaran. "Residue type" is a well established concept in biochemistry: residues can be basic, charged, polar, aromatic, hydrophobic, hydrophilic, etc. when you say "residue type" this is what anybody in this field will think about. The issue here is not to be consistent with BMRB or the wwPDB, but with protein science and biochemistry in general.

As for the format being "established and implemented," I have to say that this was not at all the impression I got at Osaka. Most developers present had no translator software implemented whatsoever. They complained that two weeks to comment on the format definition was too short a time, as they had to study the dictionary, and they even ask where could the dictionary definition be found. Only XPLOR had a more or less working translator. In any case, this change is trivial for them to execute, and it is the correct thing to do. The expression "ALA 151," for example, consists of the residue name and its sequence position (two different columns in any NEF or NMR-STAR table). The combination of the two could be seen as a "residue identifier" so you can identify it in a particular sequence, but is never referred to as a "residue name."

Cheers,
Pedro



On Sep 4, 2016, at 12:02 PM, Kumaran Baskaran <notifications@github.com<mailto:notifications@github.com>> wrote:


"As the format is already made and largely implemented at this point". I disagree with this point. Till now I haven't seen any real support or output from the software developers other than CCPN.
Moreover I am still not clear with the terms "NEF consortium" and "Software developers" . I assume software developers are the part of "NEF Consortium" and I expect them to participate the GitHub activities.
I am not asking you to be consistent with BMRB, but I am asking to be consistent with majority of the community. I haven't seen ALA is called as residue_type except in NEF. I don't think NEF consortium or software developers will object when you tag ALA as residue_name. You haven't answered what happens in future if you want to add a tag for residue_type?.
But it does not matter too much, really- NO, It does matter. I have no problem to map NEF residue_type to STAR residue_name, but I am worrying about the expandability of NEF. If you try to expand NEF to accommodate more information(like residue_type), then you will be in trouble. So its better to change now.

-

**Comment by rhfogh** [comment]
I would say that the community/consortium we are dealing with are the people who are coding with or to the NEF format. And that we are past the point where we can just make a change and expect everybody to comply (assuming we ever could do that). There may not be that much already implemented, but renaming the current NEF tags would potentially force people to change existing code, and therefore such a change needs to be put up as a proposal and accepted - or at least nodded through. I would not disagree that some more active collaboration from the developers would be nice, but on principle I think we have to get some kind of accept from them, even so. If nothing else to make it clear, for future reference, that the NEF format is not changed without proper consultation. 

Maybe we could discuss this in the virtual meeting next Thursday? The best path forward is probably that you make a change proposal for tag changes, ideally gathering together all the tags that you might want changed, so we can deal with the lot at once. Eventually that should go on GitHub, so we can then go through the work of getting people to read, address, and respond to that proposal, like we need to do to for the proposals on sequence specification. I will certainly not obstruct the process - I have no objection to the tag 'residue_name' - but I do not think it is up to me to be the prime mover. 

On the philosophical point, I think it depends on whether the object you are looking at is leucine as such, or a specific leucine in a specific chain. The substance leucine has the name 'Leucine' and the type 'hydrophobic', much as an aircraft make has the name 'Boeing 737' and the type 'fixed-wing passenger aircraft', but a specific leucine has a name that matches the identifier, and the type 'leucine', much as a specific airplane has the name 'City of Glasgow' and the type 'Boeing 737'. But, as I have said above, the question before is now is practical, rather than philosophical.
