### ISSUE TITLE
Pseudo atom vs wildcard 

### ISSUE THREAD

**Issue by kumar-physics** [NMRExchangeFormat/NEF#59]
In the CSROSETTA example file pseudo atoms were used for VAL (QG1,QG2) in the chemical shift section and wildcards(HG%) were used in restraints sections. I guess these representations have its own meaning and purpose. I expect the other way, pseudo atoms in restraints and wildcards in chemical shifts.  Is there any rule saying when to use pseudo atoms and when to use wildcard?

**Comment by rhfogh** [comment]
The rule is that a wildcard expression expands to the atoms involved (e.g. VAL HG1% -> (HG11, HG12, HG13)), whereas a pseudoatom simply refers to an abstract point at the centroid of the protons involved. In restraints this makes a difference for how distances should be calculated (and whether distance restraints need to be corrected beforehand).  In a shift list the two things clearly have the same information content. I would be tempted to ban pseudoatoms in shift lists (abstract geometrical points do not really give rise to NMR signals), but on the other hand there is some sense to using pseudoatoms ifor the shifts if you use them for the restraints. But since the meaning is clear and pseudoatoms have a history, I am not sure we can prevent people from doing whta you say the ROsetta people are donig. I shall be back when I have looked at their file.

**Comment by AlisonBarrett** [comment]
Thank you for this catch. These are in fact meant as wildcards, not pseudo-atoms. I have our file-generator set up to use nef wildcards for the chemical shifts, but must have forgotten to uncomment some code before making the file I sent. I'll send a new one with this fix (as well as the fix to the other issue raised). 
Fun fact: With Rosetta, "Q" is our wildcard. For instance, QG1 would be HG1% in nef, or we could use QQG to mean HG%.
