### ISSUE TITLE
How to expand  wildcard nomenclature for a modified residue?

### ISSUE THREAD

**Issue by kumar-physics** [NMRExchangeFormat/NEF#71]
One of the example file [2mtv](https://github.com/NMRExchangeFormat/NEF/blob/master/data_0_2/CCPN_2mtv_docr.nef) contains a modified residue 6MZ.  Without the topology information or coordinate file how do I expand   'HHX%'.  I looked into the cif file downloaded from PDB and I couldn't find an atom represented as 'HH' followed by two numbers for the residue 6MZ.  
Is 'HHX%' a typo or a limitation of NEF?

**Comment by perzeus** [comment]
What Geerten told me about these cases (non-standard residues) was that their atoms will just remain “undetermined,” so, you cannot translate most wildcard atoms into particular options unless the options are trivial. From this I conclude that NEF is not meant to accurately represent non-standard residues.

Pedro

On Sep 29, 2016, at 2:28 PM, Kumaran Baskaran <notifications@github.com<mailto:notifications@github.com>> wrote:


One of the example file 2mtv<https://github.com/NMRExchangeFormat/NEF/blob/master/data_0_2/CCPN_2mtv_docr.nef> contains a modified residue 6MZ. Without the topology information or coordinate file how do I expand 'HHX%'. I looked into the cif file downloaded from PDB and I couldn't find an atom represented as 'HH' followed by two numbers for the residue 6MZ.

Is 'HHX%' a typo or a limitation of NEF?

**Comment by rhfogh** [comment]
You have found a problem that needs fixing (again, thanks), but it is not nearly as bad as you think.

Residue names refer to RCSB chemical compounds, if there is one that matches. In this case there is, so that gives you the topology information you need. Names must match that topology. HHX% does not, so it is an error. 

The origin of that error is that I had to convert the 2mtv restraints by an ad-hoc script from the original Cyana (or whatever) restraints. And that is a problem with no reliable solution - which is indeed why we are making NEF to avoid it. The restraint list contained a number of restraints to "3 6MA QH1", which by standard mapping rules should translate to 'B  3  6MZ  HHX%'. Since there is no such thing in that residue that is clearly wrong, but even looking at it I am not sure which atoms fit to the name 'QH1'. Quite likely it is the extra methyl group, whose three atoms near as I can figure out are named 'H9', 'H9C1', and 'H9C2' (sic).  But if there is any way to determine that except by guesswork and manual intervention I do not know what it is. 

Since this is a test data set we should clearly fix it for the v1.0 version. So, if you or somebody else can confirm to me that 'QH1' really does mean that methyl group, I can enter it by the only name that would fit, which is 'H9*'. It would clearly be better if someone would come up with an algorithm that would make that name mapping automatically. But I really think that the general problem of reading old restraint lists is insoluble, except by manual intervention.

Meanwhile, the right thing to do when meeting a name that does not match is to treat is an an anonymous assignment, incorporate it or skip it as your programs can handle, and issue a warning message for the user to deal with. And, in cases like this, mail the creator of the data so he can fix them.

**Comment by kumar-physics** [comment]
I suggest the following;
Its the responsibility NEF consortium to deal with this kind of issues during data exchange between different softwares, but when it comes to data deposition at the wwPDB, it has to be associated with the mmCIF coordinate file and **its better to avoid any wild cards or pseudo atoms for non standard residues** and use the actual atom names from the mmCIF file.

**Comment by rhfogh** [comment]
Kumaran:
That goes against one of the main purposes of NEF.  It was a design decision that the file should be deposited with *one, consistent* set of identifiers that match the work done by the authors and that allows you to trace the information back to source.

It is certainly a messy job to convert from user names to proper IUPAC names, especially  for non-standard residues with strange naming conventions like methyl protons that do not match each other. Do you really think you will get more reliable results if that conversion is done by whichever PhD student did the structure generation, and the original information is not deposited?

**Comment by kumar-physics** [comment]
I am NOT saying that the names should be in IUPAC. I am saying what ever in the coordinate file should be used in the NEF file **WITHOUT PSEUDO ATOMS OR WILDCARDS**  for the non standard residues. This is my suggestion.
